# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29d6cbd6ea12f2637af398eeaf4849f3d66df5cc62de6a7bcd6bffb59f3062e1f81d82c28c2535dede5a38ad0e22d53ce094ac40b8df67fcf9023c30f8c878d9

test:
  secret_key_base: 5f34e7b97eefd2c5c1b92fb86250ed1ace9ba46a8b6eb5e89908bbaf22a167be7ffff843eb184647827b2fab170e462d7eaacf2830aa27ba65429b6ee898bba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
